### PR TITLE
Several IN_MEMORY_ANALYTICAL improvements and bug fixes

### LINKED ISSUE #3436: Memgraph crashes with The label property index already exists
**Memgraph version**
3.6.2

**Environment**
Docker

**Describe the bug**
The memgraph container keeps restarting itself with the following error:

[2025-11-14 13:11:37.033] [memgraph_log] [info] Recovering metadata of 0 existence constraints.
[2025-11-14 13:11:37.033] [memgraph_log] [info] Metadata of existence constraints are recovered.
[2025-11-14 13:11:37.033] [memgraph_log] [info] Recovering metadata of 0 unique constraints.
[2025-11-14 13:11:37.033] [memgraph_log] [info] Metadata of unique constraints are recovered.
[2025-11-14 13:11:37.033] [memgraph_log] [info] Recovering metadata of 0 type constraints.
[2025-11-14 13:11:37.033] [memgraph_log] [info] Metadata of type constraints are recovered.
[2025-11-14 13:11:37.034] [memgraph_log] [info] Metadata of constraints are recovered.
[2025-11-14 13:11:37.034] [memgraph_log] [info] Recovering metadata.
[2025-11-14 13:11:37.034] [memgraph_log] [info] Recovering TTL data.
[2025-11-14 13:11:37.034] [memgraph_log] [info] TTL data recovered.
[2025-11-14 13:11:37.034] [memgraph_log] [info] Metadata recovered.
[2025-11-14 13:11:37.034] [memgraph_log] [info] Snapshot recovery successful!
[2025-11-14 13:11:37.034] [memgraph_log] [trace] Recovered epoch b00f45e3-d32f-484f-a8b0-40e683d9f513 for db memgraph
[2025-11-14 13:11:37.034] [memgraph_log] [trace] Read wal file /var/lib/memgraph/wal/20251113154411410914_current with following info: storage_uuid: c7a8d1ab-4afe-4999-9e2a-31fdb9444f27, epoch id: b00f45e3-d32f-484f-a8b0-40e683d9f513, from timestamp 1602, to_timestamp 73865, sequence number 0.
[2025-11-14 13:11:37.034] [memgraph_log] [trace] Wal file /var/lib/memgraph/wal/20251113154411410914_current will be used.
[2025-11-14 13:11:37.034] [memgraph_log] [info] Checking WAL files.
[2025-11-14 13:11:37.034] [memgraph_log] [trace] Wal file: /var/lib/memgraph/wal/20251113154411410914_current. Seq num: 0.
[2025-11-14 13:11:37.034] [memgraph_log] [trace] Checking 1st wal file: /var/lib/memgraph/wal/20251113154411410914_current.
[2025-11-14 13:11:37.034] [memgraph_log] [info] Trying to load WAL files.
[2025-11-14 13:11:37.034] [memgraph_log] [info] Trying to load WAL file /var/lib/memgraph/wal/20251113154411410914_current.
[2025-11-14 13:11:37.034] [memgraph_log] [info] WAL file contains 138 deltas.
[2025-11-14 13:11:37.034] [memgraph_log] [critical] Couldn't recover WAL deltas from /var/lib/memgraph/wal/20251113154411410914_current because of: The label property index already exists!
The label property index already exists!

**To Reproduce**
- Deploy a fresh instance of memgraph
- Set mode analytical mode, drop graph
- Create indexes
- Import the data via Spark
- Run couple of ad-hoc queries via memgraph lab
- Observe memgraph crash

### PR DESCRIPTION
**Pull request by DavIvek**
There are multiple issues we are addressing in this PR:

1. Create a snapshot when switching from analytical to transactional mode.
2. Fix a bug where deltas were being created for indexes and constraints in analytical mode, even though our documentation states that analytical mode does not generate deltas.
3. Since the text index doesn’t work in analytical mode, prevent users from creating a text index while in analytical mode.
4. Fix an issue with uniqueness constraints in analytical mode, where it is currently possible to violate them and end up in a corrupted state when switching between storage modes.

closes #3436

### CODE REVIEW

**Comment by DavIvek** [comment]
### Tracking
- [ ] **[Link to Epic/Issue]**

### Standard development
- [ ] Update unit/E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch this branch

### CI Testing Labels
- [ ] Select the appropriate CI test labels _(CI -build=**build-name** -test=**test-suite**)_

### Documentation checklist
- [x] Add the documentation label
- [x] Add the bug / feature label
- [x] Add the milestone for which this feature is intended
    - If not known, set for a later milestone
- [x] Write a release note, including added/changed clauses
    - Analytical mode now enforces stricter safety rules. Users can no longer switch to analytical mode if constraints exist, create constraints or text indexes in analytical mode, and a snapshot is automatically created when switching back to transactional mode. These changes prevent unsafe or corrupted states caused by unsupported analytical-mode operations. [#3461](https://github.com/memgraph/memgraph/pull/3461)
- [ ] **[ Documentation PR link memgraph/documentation#XXXX ]**
    - [ ] Is back linked to this development PR

File: src/storage/v2/inmemory/storage.cpp [hunk 1]
```diff
@@ -763,9 +763,14 @@ utils::BasicResult<StorageManipulationError> InMemoryStorage::InMemoryAccessor::
 
   // TODO: duplicated transaction finalization in md_deltas and deltas processing cases
   if (transaction_.deltas.empty() && transaction_.md_deltas.empty()) {
-    // We don't have to update the commit timestamp here because no one reads
-    // it.
-    mem_storage->commit_log_->MarkFinished(transaction_.start_timestamp);
+    if (storage_->storage_mode_ == StorageMode::IN_MEMORY_ANALYTICAL) {
+      // If we are in analytical we still have work to do in order for transaction changes to be visible.
+      FinalizeCommitPhaseInAnalytical();
```
Comment (as51340) [inline src/storage/v2/inmemory/storage.cpp]: Why not normal flow processing?

File: src/storage/v2/inmemory/storage.cpp [hunk 2]
```diff
@@ -889,6 +894,31 @@ utils::BasicResult<StorageManipulationError> InMemoryStorage::InMemoryAccessor::
   return *std::move(res);
 }
 
+void InMemoryStorage::InMemoryAccessor::FinalizeCommitPhaseInAnalytical() {
```
Comment (as51340) [inline src/storage/v2/inmemory/storage.cpp]: no ldt update and no update of number of comitted txns.

Comment (as51340) [reply src/storage/v2/inmemory/storage.cpp]: I understand if we don't track ldt for in_memory_analytical but not sure about the number of committed txns?

File: tests/e2e/constraints/constraints_validation.py [hunk 3]
```diff
@@ -293,5 +293,26 @@ def test_delta_release_on_unique_constraint_error(memgraph):
     assert unreleased_delta_objects_actual == 0
 
 
+def test_cant_change_to_analytical_mode_with_constraints(memgraph):
```
Comment (as51340) [inline tests/e2e/constraints/constraints_validation.py:296]: test that after create and drop constraint, storage mode can be changed

File: tests/e2e/durability/indices_not_persisted_analytical.py [hunk 4]
```diff
@@ -0,0 +1,86 @@
...
+                "IN_MEMORY_ANALYTICAL",
+            ],
+            "log_file": "indices_not_persisted_analytical_recover.log",
+            "data_directory": dir,
+        },
+    }
+
+
+def test_indices_not_persisted_in_analytical_mode():
+    data_directory = tempfile.TemporaryDirectory()
```
Comment (as51340) [inline tests/e2e/durability/indices_not_persisted_analytical.py]: don't use temp directory, we changed that at some point so it's easier to debug. Take a look at strict_sync.py test and how which dir we use there as a data directory

File: tests/e2e/durability/snapshot_recovery.py [hunk 5]
```diff
@@ -655,6 +654,40 @@ def test_recover_snapshot_uuid_and_name_update(global_snapshot):
     interactive_mg_runner.kill_all()
 
 
+def test_snapshot_on_mode_change_analytical_to_transactional():
+    data_directory = tempfile.TemporaryDirectory()
```
Comment (as51340) [inline tests/e2e/durability/snapshot_recovery.py]: same

File: src/storage/v2/disk/storage.cpp [hunk 6]
```diff
@@ -2064,7 +2064,7 @@ utils::BasicResult<StorageIndexDefinitionError, void> DiskStorage::DiskAccessor:
   auto publisher = storage_->invalidator_->invalidate_for_timestamp_wrapper(always_invalidate_plan_cache);
   publisher(0 /*timestamp is ignored*/);
 
-  transaction_.md_deltas.emplace_back(MetadataDelta::label_index_create, label);
+  AddMetadataDeltaIfTransactional(MetadataDelta::label_index_create, label);
```
Comment (as51340) [inline src/storage/v2/disk/storage.cpp]: I think for DiskAccessor you don't need to use AddMetadataDeltaIfTransactional since you know you're not in analytical

File: src/storage/v2/inmemory/storage.cpp (hunk 1 above)
Comment (as51340) [reply src/storage/v2/inmemory/storage.cpp]:
```

void InMemoryStorage::InMemoryAccessor::FinalizeCommitPhaseInAnalytical() {
  auto *mem_storage = static_cast<InMemoryStorage *>(storage_);

  {
    auto engine_guard = std::unique_lock{storage_->engine_lock_};
    commit_timestamp_.emplace(mem_storage->GetCommitTimestamp());
  }

  // Install the new point index, if needed
  mem_storage->indices_.point_index_.InstallNewPointIndex(transaction_.point_index_change_collector_,
                                                          transaction_.point_index_ctx_);

  // Call other callbacks that publish/install upon commit
  transaction_.commit_callbacks_.RunAll(*commit_timestamp_);
  mem_storage->commit_log_->MarkFinished(transaction_.start_timestamp);
  is_transaction_active_ = false;
}
```

Comment (as51340) [reply src/storage/v2/inmemory/storage.cpp]:
```

  if (storage_->storage_mode_ == StorageMode::IN_MEMORY_ANALYTICAL) {
    FinalizeCommitPhaseInAnalytical();
    return {};
  }

  // TODO: duplicated transaction finalization in md_deltas and deltas processing cases
  if (transaction_.deltas.empty() && transaction_.md_deltas.empty()) {
    // We don't have to update the commit timestamp here because no one reads
    // it.
    mem_storage->commit_log_->MarkFinished(transaction_.start_timestamp);
    return {};
  }
```

Comment (as51340) [reply src/storage/v2/inmemory/storage.cpp]: Still perf issue since we are taking engine lock, not sure if we can live with it

Comment (as51340) [reply src/storage/v2/inmemory/storage.cpp]: engine lock is needed for commit callbacks

File: src/query/interpreter.cpp [hunk 7]
```diff
@@ -4964,33 +4971,36 @@ PreparedQuery PrepareCreateSnapshotQuery(ParsedQuery parsed_query, bool in_expli
...
           break;
         case storage::InMemoryStorage::CreateSnapshotError::AbortSnapshot:
-          throw utils::BasicException("Failed to create snapshot. The current snapshot needs to be aborted.");
+          throw utils::BasicException("Failed to create snapshot. {}.",
+                                      storage::InMemoryStorage::CreateSnapshotErrorToString(maybe_path.error()));
         case storage::InMemoryStorage::CreateSnapshotError::AlreadyRunning:
-          throw utils::BasicException("Another snapshot creation is already in progress.");
         case storage::InMemoryStorage::CreateSnapshotError::NothingNewToWrite:
-          throw utils::BasicException("Nothing has been written since the last snapshot.");
+          throw utils::BasicException("{}", storage::InMemoryStorage::CreateSnapshotErrorToString(maybe_path.error()));
```
Comment (as51340) [inline src/query/interpreter.cpp]: I think BasicException accepts passing string as arg, you shouldn't need formatting {}

File: src/storage/v2/inmemory/storage.cpp [hunk 8]
```diff
@@ -2581,7 +2591,8 @@ StorageInfo InMemoryStorage::GetInfo() {
 }
 
 bool InMemoryStorage::InitializeWalFile(memgraph::replication::ReplicationEpoch &epoch) {
-  if (config_.durability.snapshot_wal_mode != Config::Durability::SnapshotWalMode::PERIODIC_SNAPSHOT_WITH_WAL) {
+  if (config_.durability.snapshot_wal_mode != Config::Durability::SnapshotWalMode::PERIODIC_SNAPSHOT_WITH_WAL ||
+      storage_mode_ == StorageMode::IN_MEMORY_ANALYTICAL) {
```
Comment (as51340) [inline src/storage/v2/inmemory/storage.cpp:2595]: I think this is not the best. It is correct in this scenario but at multiple places throughout the file we are relying on snapshot_wal_mode and only on that one. When changing storage mode, I would update snapshot_wal_mode to DISABLED and rely solely on that.

**Review by as51340 — CHANGES_REQUESTED** [review]
Good work but needs a bit of polishing

File: src/storage/v2/inmemory/storage.cpp (hunk 8 above)
Comment (as51340) [reply src/storage/v2/inmemory/storage.cpp:2595]: discussed on the call, we will leave it as it is since snapshot and wal folders mgmt are glued together at multiple places so we don't want to change that at the moment. Note for future devs: be careful since there are snapshot_wal_mode, storage_mode and storage_wal_enabled, all very connected configuration parameters. Very hard to say which one is used at which moment
