### PR TITLE
fix: Support LIMIT on both sides of a UNION

### LINKED ISSUE #3909: Query hangs when both UNION branches contain LIMIT
**Memgraph version**
Memgraph version: `3.8.1`

**Environment**
- Docker image used locally: `memgraph/memgraph:latest`
- Current explicit Docker tag for reproducible setup: `memgraph/memgraph:3.8.1-relwithdebinfo`
- Deployment: Docker
- Host OS: Windows
- Client used: `mgconsole`

**Describe the bug**
A query using `UNION` where both branches contain their own `LIMIT` does not return on Memgraph 3.8.1.
The same query returns immediately on Neo4j.

**To Reproduce**
```cypher
RETURN 1 AS x LIMIT 1
UNION
RETURN 2 AS x LIMIT 1;
```

I also reproduced the same behavior with a graph-backed variant:

```cypher
MATCH (n) DETACH DELETE n;
CREATE (:T {v: 1}), (:T {v: 2});
MATCH (n:T) RETURN n LIMIT 1
UNION
MATCH (n:T) RETURN n LIMIT 1;
```

**Expected behavior**
The query should return quickly.

**Actual behavior**
the query does not return within the timeout window and appears to hang indefinitely.

**What I checked**
I minimized the original failing query and verified the following:

- `UNION` without per-branch `LIMIT` does not hang.
- A single `LIMIT` on only one branch does not hang.
- A single branch with `LIMIT` does not hang.
- The hang appears only when both `UNION` branches contain their own `LIMIT`.

Examples that do **not** hang:

```cypher
RETURN 1 AS x UNION RETURN 2 AS x;
```

```cypher
RETURN 1 AS x LIMIT 1 UNION RETURN 2 AS x;
```

```cypher
RETURN 1 AS x UNION RETURN 2 AS x LIMIT 1;
```

**Verification Environment**
 Plain memgraph Docker image

### PR DESCRIPTION
**Pull request by colinbarry**
Fixes `UNION` so that it no longer tries `Pull`ing from an already exhausted left-hand branch.

#fix [3909](https://github.com/memgraph/memgraph/issues/3909)

### CODE REVIEW

**Comment by colinbarry** [comment]
### Tracking
- [x] **[Link to Epic/Issue]**

### Standard development
- [x] Update unit/E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch this branch

### CI Testing Labels
- [x] Select the appropriate CI test labels _(CI -build=**build-name** -test=**test-suite**)_

### Documentation checklist
- [x] Add the documentation label
- [x] Add the bug / feature label
- [x] Add the milestone for which this feature is intended
    - If not known, set for a later milestone
- [x] Write a release note, including added/changed clauses
    - Fixes hang or crash when using a `LIMIT` on both sides of a `UNION` or `UNION ALL` query. [#4065](https://github.com/memgraph/memgraph/pull/4065)

File: src/query/plan/operator.cpp [hunk 1]
```diff
@@ -11181,6 +11181,7 @@ bool Limit::LimitCursor::Pull(Frame &frame, ExecutionContext &context) {
   }
 
   // check we have not exceeded the limit before pulling
+  if (!shared_quota_) return false;
```
Comment (andrejtonev) [inline src/query/plan/operator.cpp]: The first pull initializes the shared quota.
Subsequent pulls reset the quota, but only when returning false, so no subsequent pulls should happen. What is happening exactly that this fixes?

This is different from Skip where Skip continues pulling after the quota has been exhausted.

File: tests/gql_behave/tests/memgraph_V1/features/union.feature [hunk 2]
```diff
@@ -134,3 +134,34 @@ Feature: Union
...
+
+    Scenario: Union all with limit on each branch
+        Given an empty graph
+        When executing query:
+            """
+            RETURN 1 AS x LIMIT 1 UNION ALL RETURN 2 AS x LIMIT 1
+            """
+        Then the result should be:
+            | x |
+            | 1 |
```
Comment (Josipmrden) [inline tests/gql_behave/tests/memgraph_V1/features/union.feature:166]: maybe add one with limit, other without limit, and vice versa?

File: src/query/plan/operator.cpp (hunk 1 above)
Comment (colinbarry) [reply src/query/plan/operator.cpp]: Fixed in `UnionCursor` instead

File: tests/gql_behave/tests/memgraph_V1/features/union.feature (hunk 2 above)
Comment (colinbarry) [reply tests/gql_behave/tests/memgraph_V1/features/union.feature:166]: Done

**Review by andrejtonev — APPROVED** [review]
