### PR TITLE
Fix index hints

### LINKED ISSUE #1592: Memgraph doesn't respect to Index Hinting
**Memgraph version**
2.13.0

**Environment**
CentOS 7

**Describe the bug**
Memgraph doesn't consider using the Index that is instructed to be used with `USING INDEX`.

**To Reproduce**
I have about 14 million nodes with Device label (`id` property is indexed) and about 50 thousand nodes with Topic label (`id` property is indexed). When I run the following command, the planner decides to use `Device (id)` index instead of `Topic (id)` index:

```
USING INDEX :Topic(id) MATCH (d:Device)-[:SUBSCRIBE]->(t:Topic) WHERE t.id IN ['testDevices'] AND d.id > '0' RETURN d.token, d.platform LIMIT 10000;
```

Query Plan:
```
memgraph> EXPLAIN USING INDEX :Topic(id) MATCH (d:Device)-[:SUBSCRIBE]->(t:Topic) WHERE t.id IN ['testDevices'] AND d.id > '0' RETURN d.token, d.platform LIMIT 10000;
+---------------------------------------------------+
| QUERY PLAN                                        |
+---------------------------------------------------+
| " * Limit"                                        |
| " * Produce {d.token, d.platform}"                |
| " * Filter (t :Topic), {t.id}"                    |
| " * Expand (d)-[anon1:SUBSCRIBE]->(t)"            |
| " * ScanAllByLabelPropertyRange (d :Device {id})" |
| " * Once"                                         |
+---------------------------------------------------+
```

**Expected behavior**
I expect the planner to use `Topic (id)` index:

```
+--------------------------------------------------+
| QUERY PLAN                                       |
+--------------------------------------------------+
| " * Limit"                                       |
| " * Produce {d.token, d.platform}"               |
| " * Filter (d :Device)"                          |
| " * Expand (t)<-[anon1:SUBSCRIBE]-(d)"           |
| " * ScanAllByLabelPropertyValue (t :Topic {id})" |
| " * Unwind"                                      |
| " * Once"                                        |
+--------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by DavIvek**
The issue is that even if the user gives a hint to memgraph's planner which index to use, memgraph will still generate multiple plans (with the user's hint included) and compare their costs based on its query cost estimator. 
To resolve the issue I added one more return value(from cost estimator) that tells us if the plan is generated by using index hints. Plans generated by using index hints will have bigger priority than ones that don't. 

[master < Task] PR
- [x] Check, and update documentation if necessary
- [x] Provide the full content or a guide for the final git message

To keep docs changelog up to date, one more thing to do:
- [x] Write a release note here, including added/changed clauses
- [ ] Tag someone from docs team in the comments

Release note: Index hints fixed to also work with queries that are using expanding from one node to another in their plans. 

closes #1592

### CODE REVIEW

File: src/query/plan/planner.hpp [hunk 1]
```diff
@@ -59,9 +59,9 @@ class PostProcessor final {
   }
 
   template <class TVertexCounts>
-  double EstimatePlanCost(const std::unique_ptr<LogicalOperator> &plan, TVertexCounts *vertex_counts,
-                          const SymbolTable &table) {
-    return query::plan::EstimatePlanCost(vertex_counts, table, parameters_, *plan);
+  std::pair<double, bool> EstimatePlanCost(const std::unique_ptr<LogicalOperator> &plan, TVertexCounts *vertex_counts,
+                                           const SymbolTable &table) {
+    return query::plan::EstimatePlanCost(vertex_counts, table, parameters_, *plan, index_hints_);
   }
```
Comment (antepusic) [inline src/query/plan/planner.hpp:65]:
```
double cost = post_process.EstimatePlanCost(rewritten_plan, dba, symbol_table).first;
```
The `.first` in the above line is a bit arbitrary. I think the code will be more maintainable if `EstimatePlanCost` returned a struct. That way, you can take advantage of named fields.

File: tests/benchmark/query/planner.cpp
Comment (antepusic) [inline tests/benchmark/query/planner.cpp:1]: Can you add a test that shows Memgraph will use the hinted plan instead of the equal-cost plan that doesn’t use index hints?

Comment (antepusic) [reply tests/benchmark/query/planner.cpp:1]: This PR means that there are two factors in plan selection: total cost and the presence of index hints. I think it would be a good idea to add a test showing that total cost takes precedence over index hinting, i.e. that Memgraph will prefer the less costly plan with no index hints over a more costly one with index hints.

**Review by antepusic — CHANGES_REQUESTED** [review]
Good work! Left a few comments for the sake of maintainability and thorough testing.

**Review by antepusic — APPROVED** [review]
Thanks for addressing my comments! I think this is approvable now.

**Review by Josipmrden — CHANGES_REQUESTED** [review]

**Comment by Josipmrden** [comment]
Please just alter the comments in planner.hpp to make the logic more readable

**Review by Josipmrden — APPROVED** [review]
