### PR TITLE
Fix empty aggregation returns null

### LINKED ISSUE #1474: Memgraph returns a Record with null values, Neo4j doesn't return a Record
**Memgraph version**
Memgraph 2.12

**Environment**
Memgraph in docker 

**Describe the bug**
When using collect Memgraph will return a result, Neo4j won't return the result. This causes users to change the code base, increased traction for migration. 

**To Reproduce**

No results: 
```
MATCH (subnet:Subnet)
WHERE FALSE
RETURN id(subnet) AS subnetId
```

Returns a record with null subnetId. 
```
MATCH (subnet:Subnet)
WHERE FALSE
WITH subnet, collect(subnet.ip) AS ips
RETURN id(subnet) AS subnetId
```

**Expected behavior**
Neo4j does not return results, Memgraph probably should not also.

### PR DESCRIPTION
**Pull request by as51340**
Closes #1474.

[master < Epic] PR
- [ ] Check, and update documentation if necessary
- [ ] Write E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch and the Epic branch
- [ ] Provide the full content or a guide for the final git message

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Provide the full content or a guide for the final git message

To keep docs changelog up to date, one more thing to do:
- [ ] Write a release note here, including added/changed clauses
- [ ] Tag someone from docs team in the comments

### CODE REVIEW

File: src/query/plan/operator.cpp [hunk 1]
```diff
@@ -3819,6 +3824,12 @@ UniqueCursorPtr Aggregate::MakeCursor(utils::MemoryResource *mem) const {
   return MakeUniqueCursorPtr<AggregateCursor>(mem, *this, mem);
 }
 
+auto Aggregate::AllAggregationsForCollecting() const -> bool {
```
Comment (Josipmrden) [inline src/query/plan/operator.cpp:3827]: Define the method name like a question to signify from the name that it returns a bool
e.g. `AreAllAggregationsForCollecting`

File: src/query/plan/operator.cpp [hunk 2]
```diff
@@ -3664,6 +3668,7 @@ class AggregateCursor : public Cursor {
     auto unique_values_it = agg_value->unique_values_.begin();
     auto agg_elem_it = self_.aggregations_.begin();
     const auto counts_end = agg_value->counts_.end();
+    spdlog::info("Updating agg value");
```
Comment (Josipmrden) [inline src/query/plan/operator.cpp:3671]: delete this log, I think it's going to overflow the logs

File: tests/e2e/replication/show_while_creating_invalid_state.py [hunk 3]
```diff
@@ -697,7 +697,7 @@ def test_sync_replication_when_main_is_killed():
         )
 
         # 2/
-        QUERY_TO_CHECK = "MATCH (n) RETURN COLLECT(n.name);"
+        QUERY_TO_CHECK = "MATCH (n) RETURN COUNT(n.name);"
```
Comment (Josipmrden) [inline tests/e2e/replication/show_while_creating_invalid_state.py:700]: why did you put count here?

File: tests/unit/query_plan_accumulate_aggregate.cpp [hunk 4]
```diff
@@ -277,13 +277,11 @@ TYPED_TEST(QueryPlanAggregateOps, WithoutDataWithGroupBy) {
...
     auto results = this->AggregationResults(true, false, {Aggregation::Op::COLLECT_LIST});
-    EXPECT_EQ(results.size(), 1);
-    EXPECT_EQ(results[0][0].type(), TypedValue::Type::List);
+    EXPECT_EQ(results.size(), 0);
   }
   {
     auto results = this->AggregationResults(true, false, {Aggregation::Op::COLLECT_MAP});
-    EXPECT_EQ(results.size(), 1);
-    EXPECT_EQ(results[0][0].type(), TypedValue::Type::Map);
+    EXPECT_EQ(results.size(), 0);
```
Comment (Josipmrden) [inline tests/unit/query_plan_accumulate_aggregate.cpp:284]: can you maybe add an additional gql behave test from the issue so we document it from the e2e perspective

**Review by Josipmrden — COMMENTED** [review]
Easy fix, some comments

File: tests/e2e/replication/show_while_creating_invalid_state.py (hunk 3 above)
Comment (as51340) [reply tests/e2e/replication/show_while_creating_invalid_state.py:700]: Because this test relies that aggregation will return some result. This PR basically does the change that collect(null) is not any more [] but rather nothing while count(null) is still 0

**Comment by as51340** [comment]
@vpavicic If `collect` is called on empty list, nothing will be returned. Before, the null was returned.

**Comment by vpavicic** [comment]
The `collect` function, when called on an empty list, now yields no results instead of returning `NULL`.
