### PR TITLE
Fix accessing a variable bound to a list within BFS function

### LINKED ISSUE #1375: Fix accessing a variable bound to a list within a BFS filter function
The following query works:
```
MATCH p = (:Label {id:""})<-[*BFS ..2 (r, n | r.date IN ["2023-03"])]-(:Label)
RETURN p;
```
However, the following similar query returns an error:
```
WITH ["2023-03"] AS date
MATCH p = (:Label {id:"1"})<-[*BFS ..2 (r, n | r.date IN date)]-(:Label)
RETURN p;
> Client received exception: TypedValue is of type 'null', not 'list'
```

### PR DESCRIPTION
**Pull request by DavIvek**
The following query would throw an exception: 

```
WITH ["2023-03"] AS date
MATCH p = (:Label {id:"1"})<-[*BFS ..2 (r, n | r.date IN date)]-(:Label)
RETURN p;
> Client received exception: TypedValue is of type 'null', not 'list'`
```
with changes made by this PR, it should return the same as: 

```
MATCH p = (:Label {id:""})<-[*BFS ..2 (r, n | r.date IN ["2023-03"])]-(:Label)
RETURN p;
```

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Provide the full content or a guide for the final git message

To keep docs changelog up to date, one more thing to do:
- [ ] Write a release note here, including added/changed clauses
- [ ] Tag someone from docs team in the comments

closes #1375

### CODE REVIEW

**Comment by DavIvek** [comment]
I believe that this PR is ready for review, but since this isn't part of the v2.12 release I canceled tests. With the last commit, I only added a test for the type of query that was failing before. Before that, all checks passed(except the release build that had some issues at that moment).

**Review by andrejtonev — COMMENTED** [review]
Simple change :D 
Could we clean up the code a bit.
I think it would be better to remove the pointer and return a reference from the `get_list_literal` lambda. This reference would be a dereferenced address (first case) or a reference to the temp list (second case). We could then pass the ref into the other lambdas/functions instead of relying on the pointer.

File: src/query/interpret/eval.hpp [hunk 1]
```diff
@@ -270,30 +270,28 @@ class ExpressionEvaluator : public ExpressionVisitor<TypedValue> {
   }
 
   TypedValue Visit(InListOperator &in_list) override {
-    TypedValue *_list_ptr = nullptr;
     TypedValue _list;
```
Comment (andrejtonev) [inline src/query/interpret/eval.hpp:273]: No reason to have `_list`. This was used as a local temporary object that held a copy in case pointer was null.

File: src/query/interpret/eval.hpp [hunk 2]
```diff
@@ -270,30 +270,28 @@ class ExpressionEvaluator : public ExpressionVisitor<TypedValue> {
...
     auto literal = in_list.expression1_->Accept(*this);
 
-    auto get_list_literal = [this, &in_list, &_list, &_list_ptr]() -> void {
+    auto get_list_literal = [this, &in_list]() -> TypedValue {
```
Comment (andrejtonev) [inline src/query/interpret/eval.hpp:276]: Doing a copy could be fine. Just think about the types of objects that we could be copying. 
If they are large it could be a good idea to do a reference. That way we avoid a copy in case `ReferenceExpressionEvaluator` is valid.

File: src/query/interpret/eval.hpp [hunk 3]
```diff
@@ -270,30 +270,28 @@ class ExpressionEvaluator : public ExpressionVisitor<TypedValue> {
...
-        _list_ptr = &_list;
+        return in_list.expression2_->Accept(*this);
       }
+      return *_list_ptr;
     };
 
-    auto do_list_literal_checks = [this, &literal, &_list_ptr]() -> std::optional<TypedValue> {
-      MG_ASSERT(_list_ptr, "List literal should have been defined");
-      if (_list_ptr->IsNull()) {
+    auto do_list_literal_checks = [this, &literal, &_list]() -> std::optional<TypedValue> {
```
Comment (andrejtonev) [inline src/query/interpret/eval.hpp:285]: Would rather pass the list as an argument. No real reason to have the `_list`.

File: src/query/interpret/eval.hpp [hunk 4]
```diff
@@ -312,13 +310,13 @@ class ExpressionEvaluator : public ExpressionVisitor<TypedValue> {
...
         // cache there is no need to check again as we did check first time
-        get_list_literal();
+        _list = get_list_literal();
         auto preoperational_checks = do_list_literal_checks();
         if (preoperational_checks) {
           return std::move(*preoperational_checks);
         }
         auto &cached_value = frame_change_collector_->GetCachedValue(*cached_id);
-        cached_value.CacheValue(*_list_ptr);
+        cached_value.CacheValue(_list);
```
Comment (andrejtonev) [inline src/query/interpret/eval.hpp:319]: Could the list be moved?

**Review by andrejtonev — COMMENTED** [review]
Looks good. Just a couple of comments.

File: src/query/interpret/eval.hpp (hunk 4 above)
Comment (DavIvek) [reply src/query/interpret/eval.hpp:319]: Why would we want to move _list here?

Comment (andrejtonev) [reply src/query/interpret/eval.hpp:319]: There is no reason to have the `_list`, this is now just a simple temporary object. Assuming you did `auto list = get_list_literal()` above, you could then move it into the CacheValue call, so we don't do another copy. 

If I am not missing something, the list is not needed after the CacheValue call, so could be moved.

Comment (andrejtonev) [reply src/query/interpret/eval.hpp:319]: The CacheValue is currently taking only const ref, but could be expanded to take in &&

**Review by Ignition — APPROVED** [review]
