### PR TITLE
Fix FastDiscardOfDeltas

### LINKED ISSUE #1955: `FastDiscardOfDeltas` scanning all nodes and properties on delete
**Memgraph version**
v2.16

**Environment**
Ubuntu 22.04

**Describe the bug**
If any node has been deleted in the system, and the transaction is currently the only one running, it will go through the whole dataset and scan properties.

**To Reproduce**
1. Create 10M nodes in Memgraph
2. Create 10 indices on them
3. create 5 nodes independent of those indices, and put an index on them
4. do detach delete on those nodes

i.e.
```
CREATE CONSTRAINT ON (a:TestNode) ASSERT a.Id is UNIQUE;
Create Index on :TestNode;
Create Index on :TestNode(Id);

CREATE (n:TestNode{Id:1});
CREATE (n:TestNode{Id:2});
CREATE (n:TestNode{Id:3});
CREATE (n:TestNode{Id:4});
CREATE (n:TestNode{Id:5});

MATCH (n:TestNode) RETURN n;

MATCH (n:TestNode) DELETE n;
MATCH (n:TestNode) DETACH DELETE n;
```
ensure that you have enough number of nodes and properties in the system so you can mimick this

**Expected behavior**
The nodes should have been deleted fast

**Additional context**

image

```
void InMemoryStorage::InMemoryAccessor::FastDiscardOfDeltas(uint64_t oldest_active_timestamp,
                                                            std::unique_lock<std::mutex> /*gc_guard*/) {
  auto *mem_storage = static_cast<InMemoryStorage *>(storage_);

  // STEP 1 + STEP 2
  std::list<Gid> current_deleted_vertices;
  std::list<Gid> current_deleted_edges;
  GCRapidDeltaCleanup(current_deleted_vertices, current_deleted_edges);

  // STEP 3) skip_list removals
  if (!current_deleted_vertices.empty()) {
    // 3.a) clear from indexes first

THIS PART WILL GO OVER THE WHOLE DATASET
    std::stop_source dummy;
    mem_storage->indices_.RemoveObsoleteEntries(oldest_active_timestamp, dummy.get_token());
    auto *mem_unique_constraints =
        static_cast<InMemoryUniqueConstraints *>(mem_storage->constraints_.unique_constraints_.get());
    mem_unique_constraints->RemoveObsoleteEntries(oldest_active_timestamp, dummy.get_token());

    // 3.b) remove from veretex skip_list
    auto vertex_acc = mem_storage->vertices_.access();
    for (auto gid : current_deleted_vertices) {
      vertex_acc.remove(gid);
    }
  }

  if (!current_deleted_edges.empty()) {
    // 3.c) remove from edge skip_list
    auto edge_acc = mem_storage->edges_.access();
    auto edge_metadata_acc = mem_storage->edges_metadata_.access();
    for (auto gid : current_deleted_edges) {
      edge_acc.remove(gid);
      edge_metadata_acc.remove(gid);
    }
  }
}
```

I would also put the `FastDiscardOfDeltas` in a flag, so we can disable it optionally for users that are experiencing any issues. By default the fast discard would be turned on

### LINKED ISSUE #2226: Unrelated indexes impacts the write performance of Memgraph
**Memgraph version**
2.18

Memgraph Merge on label property index`:A1(id)` with 1 related index and 299 unrelated indexes = 20 seconds 
Memgraph Merge on label propery index `:A1(id)` with 1 related index and 9 unrelated indexes = 0.6 seconds
Memgraph Merge on label propery index `:A1(id)` with 1  related index  = 0.2 seconds 

To replicate: 

```
from neo4j import GraphDatabase
import time
from time import sleep

uri = "bolt://localhost:7687"

driver = GraphDatabase.driver(uri, auth=("", ""))


def create_first_index(session):
    query = "CREATE INDEX ON :A1(id)"
    session.run(query)
    print("Index created on A1(id)")


def drop_indexes(session):
    for i in range(1, 301):
        label = f"A{i}"
        query = f"DROP INDEX ON :{label}(id)"
        session.run(query)
        print(f"Index dropped on {label}(id)")


def create_indexes(session):
    for i in range(2, 301):
        label = f"A{i}"
        query = f"CREATE INDEX ON :{label}(id)"
        session.run(query)
        print(f"Index created on {label}(id)")


def merge_nodes(session):
    query = """
    UNWIND range(1, 100000) AS i
    MERGE (a:A1 {id: i})
    RETURN count(a)
    """
    result = session.run(query)
    count = result.single()[0]
    print(f"{count} nodes merged")


def delete_data(session):
    query = """
    MATCH (a)
    DETACH DELETE a
    """
    result = session.run(query)
    print("Data deleted")


# Measure time for each operation
with driver.session() as session:

    create_first_index(session)

    # start_time = time.time()
    # create_indexes(session)
    # create_indexes_time = time.time() - start_time
    # print(f"Time taken to create indexes: {create_indexes_time} seconds")

    start_time = time.time()
    merge_nodes(session)
    merge_nodes_time = time.time() - start_time

    print(f"Time taken to merge nodes: {merge_nodes_time} seconds")

    input("Press any key to clean DB...")

    start_time = time.time()
    delete_data(session)
    delete_data_time = time.time() - start_time
    print(f"Time taken to delete data: {delete_data_time} seconds")

    start_time = time.time()
    drop_indexes(session)
    drop_indexes_time = time.time() - start_time
    print(f"Time taken to drop indexes: {drop_indexes_time} seconds")

driver.close()
```

### PR DESCRIPTION
**Pull request by DavIvek**
Instead of deleting vertices or edges and removing obsolete index entries in `FastDiscardOfDeltas`, hand over that work to the GC.

Closes #1955 , closes #2226

### CODE REVIEW

File: src/storage/v2/inmemory/storage.cpp [hunk 1]
```diff
@@ -1101,43 +1101,19 @@ void InMemoryStorage::InMemoryAccessor::GCRapidDeltaCleanup(std::list<Gid> &curr
...
-    for (auto gid : current_deleted_edges) {
-      edge_acc.remove(gid);
-      edge_metadata_acc.remove(gid);
-    }
-  }
+  // STEP 3) hand over the deleted vertices and edges to the GC
+  mem_storage->deleted_vertices_.WithLock(
+      [&](auto &deleted_vertices) { deleted_vertices.splice(deleted_vertices.end(), current_deleted_vertices); });
+  mem_storage->deleted_edges_.WithLock(
+      [&](auto &deleted_edges) { deleted_edges.splice(deleted_edges.end(), current_deleted_edges); });
```
Comment (Josipmrden) [inline src/storage/v2/inmemory/storage.cpp:1116]: @Ignition do we now even need this part of the fast discard?

File: src/storage/v2/inmemory/storage.cpp [hunk 2]
```diff
@@ -1101,43 +1101,19 @@ void InMemoryStorage::InMemoryAccessor::GCRapidDeltaCleanup(std::list<Gid> &curr
...
-void InMemoryStorage::InMemoryAccessor::FastDiscardOfDeltas(uint64_t oldest_active_timestamp,
-                                                            std::unique_lock<std::mutex> /*gc_guard*/) {
+void InMemoryStorage::InMemoryAccessor::FastDiscardOfDeltas(std::unique_lock<std::mutex> /*gc_guard*/) {
   auto *mem_storage = static_cast<InMemoryStorage *>(storage_);
 
-  // STEP 1 + STEP 2
+  // STEP 1 + STEP 2 - delta cleanup
   std::list<Gid> current_deleted_vertices;
   std::list<Gid> current_deleted_edges;
   GCRapidDeltaCleanup(current_deleted_vertices, current_deleted_edges);
```
Comment (Josipmrden) [inline src/storage/v2/inmemory/storage.cpp:1110]: If we don't need step 3, I think we can even call this without arguments perhaps?

File: src/storage/v2/inmemory/storage.cpp (hunk 1 above)
Comment (Josipmrden) [reply src/storage/v2/inmemory/storage.cpp:1116]: @DavIvek can you explain the addition of this part, not following

Comment (DavIvek) [reply src/storage/v2/inmemory/storage.cpp:1116]: This is used to inform gc about deleted vertices.

**Review by Josipmrden — APPROVED** [review]

File: src/storage/v2/inmemory/storage.cpp (hunk 1 above)
Comment (DavIvek) [reply src/storage/v2/inmemory/storage.cpp:1116]: But maybe locking isn't necessary here.

**Comment by DavIvek** [comment]
### Tracking
- [ ] **[Link to Epic/Issue]**


### Standard development
- [ ] Update unit/E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch this branch


### CI Testing Labels
- [ ] Select the appropriate CI test labels _(CI -build=**build-name** -test=**test-suite**)_


### Documentation checklist
- [ ] Add the documentation label
- [ ] Add the bug / feature label
- [ ] Add the milestone for which this feature is intended
    - If not known, set for a later milestone
- [ ] Write a release note, including added/changed clauses
    - **[ Release note text ]**
- [ ] **[ Documentation PR link memgraph/documentation#XXXX ]**
    - [ ] Is back linked to this development PR
- [ ] **[ Tag someone from docs team ]**

File: src/storage/v2/inmemory/storage.cpp (hunk 1 above)
Comment (Ignition) [reply src/storage/v2/inmemory/storage.cpp]: uncontended spin lock which maybe not required, keep it in for now, reason about it another time.

File: src/storage/v2/inmemory/storage.cpp (hunk 2 above)
Comment (Ignition) [reply src/storage/v2/inmemory/storage.cpp]: Step 3 is required

**Comment by kgolubic** [comment]
For release note I'll use:

- Optimized the deletion process for nodes and edges by deferring the removal of obsolete index entries to the garbage collector (GC). This change improves deletion performance by reclaiming memory after the GC cycle instead of immediately.
[#2242](https://github.com/memgraph/memgraph/pull/2242)
