### PR TITLE
Database specific memory tracking

### LINKED ISSUE #3087: Implement per database memory usage control
- [ ] Track memory usage per each database
- [ ] Expose memory usage under monitoring
- [ ] Limit memory usage per database

## Related

* https://github.com/memgraph/memgraph/issues/1255

### LINKED ISSUE #3937: No per-tenant RAM quota in enterprise multi-tenant deployments
## Description
In enterprise multi-tenant deployments, there is no mechanism to limit RAM usage per tenant. This creates a "noisy neighbour" problem where one tenant's memory-intensive workload can degrade or crash workloads for all other tenants on the same instance.

Since the common pattern is one user per tenant, a user-level memory quota would effectively provide per-tenant isolation.

## Expected Behaviour
A configurable RAM quota per tenant (or per user) prevents any single tenant from exhausting available memory, improving reliability and predictability for all tenants.

## Actual Behaviour
All tenants share total available RAM with no isolation. No per-tenant or per-user memory limit can be set.

## Environment
- Memgraph version: *unknown — please add before posting*
- Edition: Enterprise

## Additional Context
This is an exploratory interest rather than a reported production issue; priority is low.

### PR DESCRIPTION
**Pull request by andrejtonev**
Adds per-database memory tracking and a **Tenant Profiles** feature that lets operators cap memory usage per database. Every allocation inside a database — storage, vector indices, query execution — is attributed to a per-DB tracker hierarchy. That hierarchy feeds into both the global domain trackers (license enforcement) and a per-DB cap tracker (tenant enforcement).

---

### Tracker Hierarchy

Each `Database` owns four `MemoryTracker` instances. Declaration order in `database.hpp` is destruction-order-sensitive — C++ destructs members in reverse declaration order, so `db_arena_` must be declared last. Its destructor purges the arena and fires extent hooks that dereference tracker pointers; those trackers must still be alive at that point.

**Global license enforcement** (`total_memory_tracker` — no parent)
```
total_memory_tracker
├── graph_memory_tracker              (storage + query domain; AI Platform license limit)
│   ├── db_memory_tracker_            (skip lists, delta slabs, indices)  ─┐
│   │                                                                       ├─ also child of db_total_memory_tracker_
│   └── [query bytes via arena hooks, not a tracker child — see below]     │
│                                                                           │
└── vector_index_memory_tracker       (vector index domain; AI Platform license limit)
    └── db_embedding_memory_tracker_  (usearch mmap allocations)          ─┘
```

**Per-DB tenant cap** (`db_total_memory_tracker_` — no parent)
```
db_total_memory_tracker_
├── db_memory_tracker_            (also child of graph_memory_tracker above)
├── db_embedding_memory_tracker_  (also child of vector_index_memory_tracker above)
└── db_query_memory_tracker_      (PMR allocations inside query execution)
      ↳ only one parent (db_total_memory_tracker_); no graph_memory_tracker parent.
        Query bytes reach graph_memory_tracker via the default arena's extent hooks.
        A second tracker parent would double-count them.
```

Storage and embedding allocations are counted in exactly three trackers — per-DB domain tracker → global domain tracker → per-DB cap. Query allocations are counted in two — `db_query_memory_tracker_` → `db_total_memory_tracker_`, with domain aggregation happening via arena extent hooks rather than a tracker parent. Each tracker represents a distinct logical scope; no byte is counted twice. No lock overhead beyond the tracker atomics.

---

#### `DbArena` — jemalloc extent hooks

Each `Database` owns a dedicated jemalloc arena with custom `DbArenaHooks`. The hooks fire on every `extent_alloc` (committed memory grows → `Alloc`) and `extent_decommit`/`extent_dalloc` (memory returned to OS → `Free`), attributing committed virtual memory accurately to `db_memory_tracker_` without intercepting every malloc.

Destructor ordering: **purge** (hooks still live → tracker decremented) → **restore default hooks atomically** via `je_mallctl` → **release index** to `ArenaPool`. This prevents use-after-free in jemalloc's background thread.

**`ArenaPool`** recycles arena indices across `Database` lifetimes. jemalloc never destroys arena metadata once created; the pool prevents unbounded metadata growth in long-running multi-tenant processes.

#### Storage allocations — two paths to the arena

| Path | Used by |
|------|---------|
| `DbAwareAllocator<T>` reads `tls_db_arena_idx` | `SkipList`, `LRUCache`, `ConcurrentUnorderedMap`, `SmallVector` |
| `ArenaMemoryResource(arena_idx)` as PMR upstream | `delta_container` → `PageSlabMemoryResource` (delta slab pages) |

Both route allocations into arena N via `je_mallocx(MALLOCX_ARENA(N))`, so extent hooks fire and `db_memory_tracker_` is updated.

#### Vector index allocations — TLS tracker scope

`config.db_embedding_memory_tracker = &db_embedding_memory_tracker_` is passed via `storage::Config` down to the index layer. Before constructing a usearch index, `TrackedVectorAllocatorMemoryTrackerScope{tracker}` sets `tls_tracked_vector_allocator_memory_tracker`. `TrackedVectorAllocator` reads that TLS at construction and stores `tracker_`, so all mmap calls inside usearch are reported to `db_embedding_memory_tracker_`.

This path uses application-level mmap accounting rather than arena extent hooks. That is intentional: usearch mmap calls bypass jemalloc entirely, so extent hooks would not fire for them. The TLS tracker scope is the correct interception point here.

#### Query allocations — PMR chain

```
QueryAllocator(db_query_memory_tracker_)
  TrackingMemoryResource          ← reports bytes to db_query_memory_tracker_
    ResourceWithOutOfMemoryException
      MonotonicBufferResource
        PoolResource               ← handed to query executors
```

`TrackingMemoryResource` is a new PMR resource that calls `tracker_->Alloc/Free` around every upstream allocation without changing the global allocator or thread arena state. Triggers use the same chain via `db_acc->DbQueryMemoryTracker()`.

---

### Tenant Profiles

Named memory-limit profiles attachable to databases, enforced via `db_total_memory_tracker_.SetHardLimit(bytes)`.

```cypher
CREATE TENANT PROFILE "gold" WITH MEMORY LIMIT 4GB;
ALTER TENANT PROFILE "gold" WITH MEMORY LIMIT 8GB;
SET TENANT PROFILE "gold" ON DATABASE mydb;
REMOVE TENANT PROFILE FROM DATABASE mydb;
DROP TENANT PROFILE "gold";   -- rejected if databases still attached
SHOW TENANT PROFILES;
```

Stored durably in the KV store (`tenant_profile:<name>`, `db_tenant_profile:<db_name>`). `AttachToDatabase` uses `PutMultiple` for an atomic batch write. Profiles survive restart — `RestoreTenantProfiles_()` re-applies limits on startup, skipping mappings whose target database no longer exists. Replicated to replicas via `TenantProfileRpc` (5 actions: `CREATE`, `ALTER`, `DROP`, `SET_ON_DATABASE`, `REMOVE_FROM_DATABASE`).

---

### New Queries

```cypher
SHOW STORAGE INFO ON DATABASE mydb;
-- New fields: db_memory_tracked, db_peak_memory_tracked,
--             db_storage_memory_tracked, db_embedding_memory_tracked, db_query_memory_tracked

SHOW MEMORY INFO;
-- Per-DB memory overview across all databases: current and peak tracked bytes per tracker,
-- active tenant profile name, and configured memory limit for each database
```

---

### Infrastructure Changes

| Component | Change |
|-----------|--------|
| `global_memory_control.cpp` | Custom `my_alloc`/`my_dalloc` hooks replaced by shared `InitDbArenaHooks` used by all DB arenas |
| `delta_container` | `ArenaMemoryResource` as upstream for `PageSlabMemoryResource`; move ctor/assign call `set_upstream(&arena_upstream_)` to fix self-referential pointer after move |
| `SkipList`, `SmallVector`, `LRUCache`, `ConcurrentUnorderedMap` | Templated on allocator to accept `DbAwareAllocator` |

### CODE REVIEW

**Comment by andrejtonev** [comment]
Git commit description, explain the changes you made here

---
__*Leave above in PR description, copy the below into a comment*__
___

### Tracking
- [ ] **[Link to Epic/Issue]**

### Standard development
- [x] Update unit/E2E tests
- [x] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch this branch

### CI Testing Labels
- [x] Select the appropriate CI test labels _(CI -build=**build-name** -test=**test-suite**)_

### Documentation checklist
- [x] Add the documentation label
- [x] Add the bug / feature label
- [x] Add the milestone for which this feature is intended
    - If not known, set for a later milestone
- [x] Write a release note, including added/changed clauses
    - feat: Each isolated database's memory usage is now tracked. Tracking is divided into longterm storage, runtime storage and vector index embeddings storage. This tracking allows the user to specify memory limits per database/tenant. Tenant profiles define the total memory limit for a particular database. Users can now manage resources more strictly and avoid "noisy" neighbors. [#3952](https://github.com/memgraph/memgraph/pull/3952)
- [x] https://github.com/memgraph/documentation/pull/1617
    - [x] Is back linked to this development PR

File: src/dbms/replication_handlers.cpp [hunk 1]
```diff
@@ -259,6 +259,90 @@ bool SystemRecoveryHandler(DbmsHandler &dbms_handler, const std::vector<storage:
...
+
+  using Action = storage::replication::TenantProfileReq::Action;
+  try {
+    switch (req.action) {
+      case Action::CREATE:
+        tp->Create(req.profile_name, req.memory_limit);
+        break;
+      case Action::ALTER: {
+        auto dbs = tp->Alter(req.profile_name, req.memory_limit);
+        MG_ASSERT(dbs, "Replicated ALTER for non-existent tenant profile '{}'", req.profile_name);
```
Comment (Ignition) [inline src/dbms/replication_handlers.cpp:302]: Unexpected request should not kill the replication server.

File: src/memory/db_arena.cpp [hunk 2]
```diff
@@ -0,0 +1,175 @@
...
+  // Note: we intentionally skip arena.N.destroy — jemalloc's arena destruction is
+  // experimental and arena indices are explicitly recycled via ArenaPool instead.
+  je_mallctl((arena_key + ".purge").c_str(), nullptr, nullptr, nullptr, 0);
+
+  // Restore the default hooks AFTER purging so jemalloc's background thread cannot
+  // call our hooks after `hooks_` is destroyed (use-after-free / null-tracker SIGSEGV).
+  // mallctl atomically swaps the hooks pointer; once it returns no new invocations
+  // of db_arena_alloc/dalloc/... will be dispatched for this arena.
+  const extent_hooks_t *base = hooks_.base_hooks;
+  je_mallctl((arena_key + ".extent_hooks").c_str(),
```
Comment (Ignition) [inline src/memory/db_arena.cpp:165]: can `je_mallctl` fail?

File: db_memory_tracking_adr.md [hunk 3]
```diff
@@ -0,0 +1,48 @@
+# ADR: Database Memory Tracking Hierarchy
```
Comment (Ignition) [inline db_memory_tracking_adr.md:1]: These *.md's should not be committed or should be moved to be an ADR

File: src/query/frontend/ast/query/tenant_profile.hpp [hunk 4]
```diff
@@ -0,0 +1,64 @@
...
+
+  enum class Action : uint8_t {
+    CREATE,
+    ALTER,
+    DROP,
+    SHOW_ALL,
+    SHOW_ONE,
+    SET_ON_DATABASE,
+    REMOVE_FROM_DATABASE,
+  } action_;
```
Comment (Ignition) [inline src/query/frontend/ast/query/tenant_profile.hpp:42]: no default member initialiser, potential UB.

File: src/utils/db_aware_allocator.hpp [hunk 5]
```diff
@@ -0,0 +1,203 @@
...
+
+  template <typename U>
+  explicit DbAwareAllocator(DbAwareAllocator<U> const & /*unused*/) noexcept {}
+
+  [[nodiscard]] T *allocate(std::size_t n) {
+    const unsigned idx = tls_db_arena_idx;
+    return DbAllocate<T>(n, idx);
+  }
+
+  void deallocate(T *p, std::size_t n) noexcept {
```
Comment (Ignition) [inline src/utils/db_aware_allocator.hpp:166]: API gives pointer of unknown allocator origin, in DEBUG build can we check against je_mallctl("arenas.lookup", ...)?

File: src/utils/db_aware_allocator.hpp [hunk 6]
```diff
@@ -0,0 +1,203 @@
...
+  explicit ArenaAwareAllocator(unsigned arena_idx = 0) noexcept : arena_idx_(arena_idx) {}
+
+  template <typename U>
+  explicit ArenaAwareAllocator(ArenaAwareAllocator<U> const &other) noexcept : arena_idx_(other.arena_idx_) {}
+
+  unsigned arena_idx() const noexcept { return arena_idx_; }
+
+  [[nodiscard]] T *allocate(std::size_t n) { return DbAllocate<T>(n, arena_idx_); }
+
+  void deallocate(T *p, std::size_t n) noexcept {
```
Comment (Ignition) [inline src/utils/db_aware_allocator.hpp]: same

File: src/memory/db_arena.hpp [hunk 7]
```diff
@@ -0,0 +1,283 @@
...
+class ArenaMemoryResource final : public std::pmr::memory_resource {
+ public:
+  explicit ArenaMemoryResource(unsigned arena_idx) noexcept : arena_idx_(arena_idx) {}
+
+ private:
+  void *do_allocate(std::size_t bytes, std::size_t alignment) override {
+    return DbAllocateBytes(bytes, arena_idx_, alignment);
+  }
+
+  void do_deallocate(void *p, std::size_t bytes, std::size_t alignment) noexcept override {
```
Comment (Ignition) [inline src/memory/db_arena.hpp]: same

File: src/storage/v2/durability/snapshot.cpp [hunk 8]
```diff
@@ -1121,7 +1122,7 @@ void RecoverOnMultipleThreads(size_t thread_count, const TFunc &func, const std:
   {
     std::atomic<uint64_t> batch_counter = 0;
     thread_count = std::min(thread_count, batches.size());
-    std::vector<std::jthread> threads;
+    std::vector<memory::DbAwareThread> threads;
```
Comment (Ignition) [inline src/storage/v2/durability/snapshot.cpp:1125]: there are other `std::vector<std::jthread>` in MultiThreadedWorkflow does that also need to change.

File: src/storage/v2/delta_container.hpp [hunk 9]
```diff
@@ -217,17 +218,49 @@ struct delta_container {
...
+  {
+  }
+
   // move ctr: needed because of size_
   delta_container(delta_container &&other) noexcept
-      : memory_resource_{std::move(other.memory_resource_)},
+      :
+#if USE_JEMALLOC
+        arena_upstream_{std::move(other.arena_upstream_)},
+#endif
```
Comment (Ignition) [inline src/storage/v2/delta_container.hpp]: Dislike USE_JEMALLOC here, can we restructure so that upstream just works

File: src/dbms/tenant_profiles.cpp [hunk 10]
```diff
@@ -0,0 +1,198 @@
...
+      for (const auto &db : profile.databases) {
+        db_to_profile_[db] = profile.name;
+      }
+      profiles_.emplace(std::move(name), std::move(profile));
+    } catch (const nlohmann::json::parse_error &e) {
+      spdlog::warn("Failed to parse tenant profile '{}': {}", name, e.what());
+    }
+  }
+
+  if (!durability_->DeletePrefix(kLegacyDbMappingPrefix)) {
```
Comment (andrejtonev) [inline src/dbms/tenant_profiles.cpp]: this is not needed

File: src/dbms/tenant_profiles.cpp [hunk 11]
```diff
@@ -0,0 +1,198 @@
...
+  TenantProfiles::Profile profile;
+  profile.name = name;
+  if (json.contains("memory_limit")) profile.memory_limit = json["memory_limit"].get<int64_t>();
+  if (json.contains("databases")) profile.databases = json["databases"].get<std::unordered_set<std::string>>();
+  return profile;
+}
+
+}  // namespace
+
+std::string TenantProfiles::ProfileToJson(const Profile &profile) {
```
Comment (andrejtonev) [inline src/dbms/tenant_profiles.cpp]: pass back json or we actually want the string?

File: src/dbms/tenant_profiles.cpp [hunk 12]
```diff
@@ -0,0 +1,198 @@
...
+
+TenantProfiles::TenantProfiles(kvstore::KVStore &durability) : durability_{&durability} {
+  auto existing_version = durability_->Get(kVersionKey);
+  if (!existing_version || *existing_version != kVersion) {
+    durability_->Put(kVersionKey, kVersion);
+  }
+
+  for (auto it = durability_->begin(std::string{kPrefix}); it != durability_->end(std::string{kPrefix}); ++it) {
+    const auto &[key, value] = *it;
+    auto name = key.substr(kPrefix.size());
```
Comment (andrejtonev) [inline src/dbms/tenant_profiles.cpp]: is this string_view? can it be if not?

File: src/dbms/tenant_profiles.cpp [hunk 13]
```diff
@@ -0,0 +1,198 @@
...
+  if (!durability_->DeletePrefix(kLegacyDbMappingPrefix)) {
+    spdlog::warn("Failed to remove legacy tenant profile database mapping keys.");
+  }
+
+  spdlog::info("Restored {} tenant profile(s)", profiles_.size());
+}
+
+bool TenantProfiles::Create(std::string_view name, int64_t memory_limit) {
+  const std::unique_lock lock{mutex_};
+  if (profiles_.contains(std::string{name})) return false;
```
Comment (andrejtonev) [inline src/dbms/tenant_profiles.cpp]: maybe add enum for different types of error

File: src/dbms/tenant_profiles.hpp [hunk 14]
```diff
@@ -0,0 +1,64 @@
...
+  bool RenameDatabase(std::string_view old_name, std::string_view new_name);
+  std::optional<std::string> GetProfileForDatabase(std::string_view db_name) const;
+
+ private:
+  static std::string ProfileToJson(const Profile &profile);
+
+  mutable std::shared_mutex mutex_;
+  kvstore::KVStore *durability_;
+  std::unordered_map<std::string, Profile> profiles_;
+  std::unordered_map<std::string, std::string> db_to_profile_;  // db_name → profile_name
```
Comment (andrejtonev) [inline src/dbms/tenant_profiles.hpp]: try using heterogeneous lookup

File: src/dbms/tenant_profiles.hpp [hunk 15]
```diff
@@ -0,0 +1,64 @@
...
+  bool DetachFromDatabase(std::string_view db_name);
+  bool RenameDatabase(std::string_view old_name, std::string_view new_name);
+  std::optional<std::string> GetProfileForDatabase(std::string_view db_name) const;
+
+ private:
+  static std::string ProfileToJson(const Profile &profile);
+
+  mutable std::shared_mutex mutex_;
+  kvstore::KVStore *durability_;
+  std::unordered_map<std::string, Profile> profiles_;
```
Comment (andrejtonev) [inline src/dbms/tenant_profiles.hpp]: think about a set with operator== on the profile name

Comment (andrejtonev) [reply src/dbms/tenant_profiles.hpp]: is this even needed? we can just use the kvstore. 
maybe needed if show queries use it and kvstore proves to be slow

File: src/dbms/tenant_profiles.cpp [hunk 16]
```diff
@@ -0,0 +1,198 @@
...
+std::optional<std::unordered_set<std::string>> TenantProfiles::Alter(std::string_view name, int64_t memory_limit) {
+  const std::unique_lock lock{mutex_};
+  auto it = profiles_.find(std::string{name});
+  if (it == profiles_.end()) return std::nullopt;
+
+  auto updated = it->second;
+  updated.memory_limit = memory_limit;
+  if (!durability_->Put(ProfileKey(updated.name), ProfileToJson(updated))) return std::nullopt;
+
+  it->second.memory_limit = memory_limit;
```
Comment (andrejtonev) [inline src/dbms/tenant_profiles.cpp]: if we do end up using the cached map, add comments to explain that you are first updating durable info and then updating the inmemory one

File: src/dbms/tenant_profiles.cpp [hunk 17]
```diff
@@ -0,0 +1,198 @@
...
+  for (const auto &[_, profile] : profiles_) {
+    result.push_back(profile);
+  }
+  return result;
+}
+
+std::optional<int64_t> TenantProfiles::AttachToDatabase(std::string_view profile_name, std::string_view db_name) {
+  const std::unique_lock lock{mutex_};
+  auto pit = profiles_.find(std::string{profile_name});
+  if (pit == profiles_.end()) return std::nullopt;
```
Comment (andrejtonev) [inline src/dbms/tenant_profiles.cpp]: error enum

File: src/dbms/tenant_profiles.cpp [hunk 18]
```diff
@@ -0,0 +1,198 @@
...
+  }
+  pit->second.databases.insert(std::string{db_name});
+  db_to_profile_[std::string{db_name}] = std::string{profile_name};
+  return pit->second.memory_limit;
+}
+
+bool TenantProfiles::DetachFromDatabase(std::string_view db_name) {
+  const std::unique_lock lock{mutex_};
+  auto dit = db_to_profile_.find(std::string{db_name});
+  if (dit == db_to_profile_.end()) return false;
```
Comment (andrejtonev) [inline src/dbms/tenant_profiles.cpp]: is this a failure?

Comment (andrejtonev) [reply src/dbms/tenant_profiles.cpp]: if so add error enum

File: src/dbms/rpc.hpp [hunk 19]
```diff
@@ -139,6 +139,51 @@ struct RenameDatabaseRes {
...
+        db_name(db_name),
+        memory_limit(memory_limit) {}
+
+  utils::UUID main_uuid;
+  uint64_t expected_group_timestamp{0};
+  uint64_t new_group_timestamp{0};
+  Action action{Action::CREATE};
+  std::string profile_name;
+  std::string db_name;
+  int64_t memory_limit{0};
```
Comment (andrejtonev) [inline src/dbms/rpc.hpp]: can we just use Profile?

File: src/dbms/replication_handlers.cpp [hunk 20]
```diff
@@ -258,6 +258,134 @@ bool SystemRecoveryHandler(DbmsHandler &dbms_handler, const std::vector<storage:
...
+    spdlog::warn("TenantProfileHandler: tenant_profiles not initialized");
+    rpc::SendFinalResponse(res, request_version, res_builder);
+    return;
+  }
+
+  using Action = storage::replication::TenantProfileReq::Action;
+  try {
+    switch (req.action) {
+      case Action::CREATE:
+        tp->Create(req.profile_name, req.memory_limit);
```
Comment (andrejtonev) [inline src/dbms/replication_handlers.cpp]: check return

File: src/dbms/replication_handlers.cpp [hunk 21]
```diff
@@ -258,6 +258,134 @@ bool SystemRecoveryHandler(DbmsHandler &dbms_handler, const std::vector<storage:
...
+          return;
+        }
+        for (const auto &db_name : *dbs) {
+          try {
+            auto db_acc = dbms_handler.Get(db_name);
+            if (req.memory_limit > 0) {
+              db_acc.get()->SetTenantMemoryLimit(req.memory_limit);
+            } else {
+              db_acc.get()->ClearTenantMemoryLimit();
+            }
```
Comment (andrejtonev) [inline src/dbms/replication_handlers.cpp]: Should be encapsulated in the Set function

File: src/dbms/replication_handlers.cpp [hunk 22]
```diff
@@ -258,6 +258,134 @@ bool SystemRecoveryHandler(DbmsHandler &dbms_handler, const std::vector<storage:
...
+          rpc::SendFinalResponse(res, request_version, res_builder);
+          return;
+        }
+        try {
+          auto db_acc = dbms_handler.Get(req.db_name);
+          if (*limit > 0) {
+            db_acc.get()->SetTenantMemoryLimit(*limit);
+          } else {
+            db_acc.get()->ClearTenantMemoryLimit();
+          }
```
Comment (andrejtonev) [inline src/dbms/replication_handlers.cpp]: encapsulated in Set

File: src/dbms/replication_handlers.cpp [hunk 23]
```diff
@@ -258,6 +258,134 @@ bool SystemRecoveryHandler(DbmsHandler &dbms_handler, const std::vector<storage:
...
+          spdlog::warn(
+              "TenantProfileHandler: REMOVE_FROM_DATABASE — db '{}' not found on replica, skipping limit clear",
+              req.db_name);
+        }
+        break;
+      }
+      default:
+        spdlog::warn("TenantProfileHandler: unknown action {}", static_cast<uint8_t>(req.action));
+        rpc::SendFinalResponse(res, request_version, res_builder);
+        return;
```
Comment (andrejtonev) [inline src/dbms/replication_handlers.cpp]: instead of all of these send return, maybe set res to true by default, on an error set to false and drop down

File: src/dbms/dbms_handler.hpp [hunk 24]
```diff
@@ -473,6 +476,17 @@ class DbmsHandler {
 
   static void RecoverStorageReplication(DatabaseAccess db_acc, replication::RoleMainData &role_main_data);
 
+#ifdef MG_ENTERPRISE
```
Comment (andrejtonev) [inline src/dbms/dbms_handler.hpp:483]: audit all MG_ENTERPRISE encapsulations of tenant code

File: src/dbms/tenant_profiles.hpp [hunk 25]
```diff
@@ -0,0 +1,64 @@
...
+#include <string_view>
+#include <unordered_map>
+#include <unordered_set>
+#include <vector>
+
+#include "kvstore/kvstore.hpp"
+
+namespace memgraph::dbms {
+
+class TenantProfiles {
```
Comment (andrejtonev) [inline src/dbms/tenant_profiles.hpp:31]: should be under MG_ENTERPRISE
best way is to make a shell class for Community and hide the logic only

File: src/dbms/dbms_handler.hpp [hunk 26]
```diff
@@ -473,6 +476,17 @@ class DbmsHandler {
...
+  TenantProfiles *tenant_profiles() { return tenant_profiles_.get(); }
```
Comment (andrejtonev) [inline src/dbms/dbms_handler.hpp]: do we need both tenant_profiles() and all the api below

File: src/dbms/replication_handlers.cpp [hunk 27]
```diff
@@ -258,6 +258,134 @@ bool SystemRecoveryHandler(DbmsHandler &dbms_handler, const std::vector<storage:
...
+  }
+
+  using Action = storage::replication::TenantProfileReq::Action;
+  try {
+    switch (req.action) {
+      case Action::CREATE:
+        tp->Create(req.profile_name, req.memory_limit);
+        break;
+      case Action::ALTER: {
+        auto dbs = tp->Alter(req.profile_name, req.memory_limit);
```
Comment (andrejtonev) [inline src/dbms/replication_handlers.cpp]: general comment
can we use the dbms_handler's api instead of reimplementing the same thing twice

File: src/dbms/dbms_handler.hpp [hunk 28]
```diff
@@ -659,7 +683,8 @@ class DbmsHandler {
   storage::Config default_config_;                     //!< Storage configuration used when creating new databases
   DatabaseHandler db_handler_;                         //!< multi-tenancy storage handler
   // TODO: move to be common
-  std::unique_ptr<kvstore::KVStore> durability_;  //!< list of active dbs (pointer so we can postpone its creation)
+  std::unique_ptr<kvstore::KVStore> durability_;     //!< list of active dbs (pointer so we can postpone its creation)
+  std::unique_ptr<TenantProfiles> tenant_profiles_;  //!< per-DB resource profiles (created after durability_)
```
Comment (andrejtonev) [inline src/dbms/dbms_handler.hpp:705]: any reason these are unique ptr?

File: src/dbms/dbms_handler.cpp [hunk 29]
```diff
@@ -415,6 +432,117 @@ struct CreateDatabase : memgraph::system::ISystemAction {
...
+    case TenantProfiles::DropResult::NOT_FOUND:
+      throw query::QueryRuntimeException("Tenant profile '{}' not found.", name);
+    case TenantProfiles::DropResult::HAS_ATTACHED_DATABASES:
+      throw query::QueryRuntimeException("Tenant profile '{}' has databases attached. Detach all databases first.",
+                                         name);
+    case TenantProfiles::DropResult::DURABILITY_ERROR:
+      throw query::QueryRuntimeException("Failed to persist deletion of tenant profile '{}'. Disk I/O error.", name);
+  }
+  if (sys_txn) {
+    sys_txn->AddAction<TenantProfileAction>(TenantProfileAction::Action::DROP, name, "", 0);
```
Comment (andrejtonev) [inline src/dbms/dbms_handler.cpp]: if 0 is a special value create a constexpr named variable instead of putting "0"

File: src/dbms/database.hpp [hunk 30]
```diff
@@ -180,7 +196,50 @@ class Database {
...
+
+  /// Vector index (embedding) memory only. Tracked via per-DB arena hooks.
+  int64_t DbEmbeddingMemoryUsage() const noexcept { return db_embedding_memory_tracker_.Amount(); }
+
+  /// Query execution (PMR) memory only. Tracked via TrackingMemoryResource.
+  int64_t DbQueryMemoryUsage() const noexcept { return db_query_memory_tracker_.Amount(); }
+
+  utils::MemoryTracker *DbQueryMemoryTracker() noexcept { return &db_query_memory_tracker_; }
+
+  void SetTenantMemoryLimit(int64_t bytes) { db_total_memory_tracker_.SetHardLimit(bytes); }
```
Comment (andrejtonev) [inline src/dbms/database.hpp:212]: handle 0 as reset

Comment (andrejtonev) [reply src/dbms/database.hpp:212]: or pass it in to sethardlimit, not sure exactly

**Review by andrejtonev — COMMENTED** [review]
Storage level Tenant Profile review

File: src/query/frontend/opencypher/grammar/MemgraphCypher.g4 [hunk 31]
```diff
@@ -895,6 +901,26 @@ userProfileQuery : createUserProfile
...
+createTenantProfile : CREATE TENANT PROFILE profile=symbolicName LIMIT tenantLimitList ;
+alterTenantProfile  : ALTER TENANT PROFILE profile=symbolicName SET tenantLimitList ;
+dropTenantProfile   : DROP TENANT PROFILE profile=symbolicName ;
+showTenantProfiles  : SHOW TENANT PROFILES ;
+showTenantProfile   : SHOW TENANT PROFILE profile=symbolicName ;
+setTenantProfileOnDatabase    : SET TENANT PROFILE ON DATABASE db=symbolicName TO profile=symbolicName ;
+removeTenantProfileFromDatabase : REMOVE TENANT PROFILE FROM DATABASE db=symbolicName ;
+
+tenantLimitList : tenantLimitKV ( ',' tenantLimitKV )* ;
+tenantLimitKV   : key=symbolicName val=limitValue ;
```
Comment (andrejtonev) [inline src/query/frontend/opencypher/grammar/MemgraphCypher.g4]: reuse listOfLimits
double check if that visitor handles only supported user profile limits or is generic

File: src/query/frontend/opencypher/grammar/MemgraphCypher.g4 [hunk 32]
```diff
@@ -913,6 +939,9 @@ showDescriptions
     : SHOW DESCRIPTIONS
     ;
 
+systemInfoQuery : SHOW ( storageInfo | buildInfo | activeUsersInfo | licenseInfo ) ;
```
Comment (andrejtonev) [inline src/query/frontend/opencypher/grammar/MemgraphCypher.g4:981]: comment that this is an overwriting from cypher.g4

File: src/query/frontend/ast/cypher_main_visitor.cpp [hunk 33]
```diff
@@ -200,6 +203,78 @@ antlrcpp::Any CypherMainVisitor::visitSystemInfoQuery(MemgraphCypher::SystemInfo
...
+
+antlrcpp::Any CypherMainVisitor::visitCreateTenantProfile(MemgraphCypher::CreateTenantProfileContext *ctx) {
+  auto *q = storage_->Create<TenantProfileQuery>();
+  q->action_ = TenantProfileQuery::Action::CREATE;
+  q->profile_name_ = std::any_cast<std::string>(ctx->profile->accept(this));
+  for (auto *kv : ctx->tenantLimitList()->tenantLimitKV()) {
+    auto key = utils::ToLowerCase(std::any_cast<std::string>(kv->key->accept(this)));
+    auto value = VisitLimitValue(kv->val, this);
+    q->limits_.emplace_back(key, value);
+  }
```
Comment (andrejtonev) [inline src/query/frontend/ast/cypher_main_visitor.cpp]: either reuse limitKV or create another visitor, so we don't need to copy paste this loop everywhere

File: src/query/frontend/stripped_lexer_constants.hpp [hunk 34]
```diff
@@ -329,6 +329,7 @@ const trie::Trie kKeywords = {"aborting",
                               "storage",
                               "stream",
                               "streams",
+                              "tenant",
```
Comment (andrejtonev) [inline src/query/frontend/stripped_lexer_constants.hpp:332]: missing memory?

File: src/query/interpreter.cpp [hunk 35]
```diff
@@ -8194,6 +8312,163 @@ PreparedQuery PrepareShowSchemaInfoQuery(const ParsedQuery &parsed_query, Curren
...
+        lv.mem_limit.value = static_cast<uint64_t>(val.ValueInt());
+      } else {
+        throw QueryException("Expected a positive integer for limit '{}'", key);
+      }
+    }
+  }
+
+  auto extract_memory_limit = [](const TenantProfileQuery::limits_t &limits) -> int64_t {
+    for (const auto &[key, lv] : limits) {
+      if (key != "memory_limit") {
```
Comment (andrejtonev) [inline src/query/interpreter.cpp]: create a consterxpr named variable instead of "memory_limit"

File: src/query/interpreter.cpp [hunk 36]
```diff
@@ -8194,6 +8312,163 @@ PreparedQuery PrepareShowSchemaInfoQuery(const ParsedQuery &parsed_query, Curren
...
+        return result;
+      }
+      if (lv.type == UserProfileQuery::LimitValueResult::Type::UNLIMITED) {
+        return 0;
+      }
+    }
+    return 0;
+  };
+
+  auto join_strings = [](const std::unordered_set<std::string> &set) {
```
Comment (andrejtonev) [inline src/query/interpreter.cpp]: there should be utils::Join

**Review by andrejtonev — COMMENTED** [review]
Query level Tenant Profile review

File: src/memory/db_arena.cpp [hunk 37]
```diff
@@ -0,0 +1,492 @@
...
+
+  // 3. Try create new arena
+  unsigned new_idx = 0;
+  try {
+    if (ConsumeFailureInjection(testing::ArenaPoolFailureInjection::AcquireArenaCreate)) {
+      throw std::runtime_error("Injected ArenaPool arena create failure");
+    }
+    new_idx = GlobalArenaPool::Instance().Acquire();
+  } catch (...) {
+    ++first_arena_use_count_;
```
Comment (Ignition) [inline src/memory/db_arena.cpp:340]: silent fallback, any tracking/logging?

File: src/query/stream/sources.cpp [hunk 38]
```diff
@@ -11,14 +11,29 @@
...
 
+#include "memory/db_arena_fwd.hpp"
 #include "query/stream/common.hpp"
 
 namespace memgraph::query::stream {
+namespace {
+auto MakeDbAwareThreadFactory(memory::ArenaPool *arena_pool) {
+  return [arena_pool](std::function<void()> task) {
+    return std::thread([arena_pool, task = std::move(task)]() mutable {
+      const memory::DbArenaScope db_arena_scope{arena_pool};
```
Comment (Ignition) [inline src/query/stream/sources.cpp:27]: Maybe should have `const utils::MemoryTracker::OutOfMemoryExceptionEnabler oom_enabler;`

**Review by Ignition — CHANGES_REQUESTED** [review]

File: src/storage/v2/storage.cpp [hunk 39]
```diff
@@ -452,8 +454,8 @@ EdgeInfoForDeletion Storage::Accessor::PrepareDeletableEdges(const std::unordere
   // add nodes which need to be detached on the other end of the edge
   if (detach) {
     for (auto *vertex_ptr : vertices) {
-      utils::small_vector<std::tuple<EdgeTypeId, Vertex *, EdgeRef>> in_edges;
-      utils::small_vector<std::tuple<EdgeTypeId, Vertex *, EdgeRef>> out_edges;
+      utils::small_vector<EdgeTriple, memory::DbAwareAllocator<EdgeTriple>> in_edges;
```
Comment (Ignition) [inline src/storage/v2/storage.cpp:476]: There are places like this which are maybe worth changing. This memory is for the duration of a particular operation and should be considered query memory, not part of the per database tracking.

File: src/storage/v2/indices/indices.cpp [hunk 40]
```diff
@@ -46,8 +46,9 @@ void Indices::RemoveVerticesFromVectorIndices(std::vector<Vertex *> const &verti
   vector_index_.RemoveVertices(vertices_to_remove);
 }
 
-void Indices::RemoveEdgesFromVectorEdgeIndices(std::vector<Edge *> const &edges_to_remove) {
-  vector_edge_index_.RemoveEdges(edges_to_remove);
+void Indices::RemoveEdgesFromVectorEdgeIndices(
+    std::list<Gid, memory::DbAwareAllocator<Gid>> const &deleted_edge_gids) const {
```
Comment (Ignition) [inline src/storage/v2/indices/indices.cpp]: this could be `std::span<const Gid>`

File: src/storage/v2/indices/vector_edge_index.cpp [hunk 41]
```diff
@@ -404,22 +408,32 @@ void VectorEdgeIndex::AbortEntries(AbortProcessor::AbortableInfo &cleanup_collec
...
-void VectorEdgeIndex::RemoveEdges(std::vector<Edge *> const &edges_to_remove) {
-  if (edges_to_remove.empty()) return;
-
-  // Lock order: uSearch mutex → edge_endpoints_mutex_ (matches SearchEdges)
-  for (const auto &[_, item_ptr] : *index_) {
-    auto guard = std::lock_guard{item_ptr->mg_index.mutex};
-    for (auto *edge : edges_to_remove) {
-      if (item_ptr->mg_index.index.contains(edge)) {
-        item_ptr->mg_index.index.remove(edge);
+void VectorEdgeIndex::RemoveEdges(std::list<Gid, memory::DbAwareAllocator<Gid>> const &deleted_edge_gids) const {
```
Comment (Ignition) [inline src/storage/v2/indices/vector_edge_index.cpp]: this could be a span

File: src/query/stream/sources.cpp (hunk 38 above)
Comment (andrejtonev) [reply src/query/stream/sources.cpp:27]: enabler is currently used only inside the cursors. If we need to have it here, that is an issue unrelated to the branch. 
Note that the streams use the interpreter and the cursors, so the behavior is the same as the normal bolt worker.

File: src/storage/v2/storage.cpp (hunk 39 above)
Comment (andrejtonev) [reply src/storage/v2/storage.cpp:476]: There are other similar local variables, but most are in GC (which is tracked as db long-lived memory anyways).
I don't think the benefits outweigh the cost to do the plumbing to get the db_query_memory_tracker here just for the DetachDelete. 
As is, we can:
1. leave it and miss-classify as long-lived
2. remove the db specific tracking and rely on the global memory tracker only

Comment (Ignition) [reply src/storage/v2/storage.cpp:476]: I'd prefer memory not be miss-classified, but that can be done in a future PR as needed.

File: tests/unit/vector_edge_index.cpp [hunk 42]
```diff
@@ -283,9 +283,7 @@ TEST_F(VectorEdgeIndexTest, RemoveEntriesTest) {
     EXPECT_EQ(maybe_deleted_edge.has_value(), true);
     ASSERT_NO_ERROR(acc->PrepareForCommitPhase(memgraph::tests::MakeMainCommitArgs()));
     auto *mem_storage = static_cast<InMemoryStorage *>(this->storage.get());
-    std::list<memgraph::storage::Gid, memgraph::memory::DbAwareAllocator<memgraph::storage::Gid>> gids_to_remove;
-    gids_to_remove.push_back(edge_gid);
-    mem_storage->indices_.vector_edge_index_.RemoveEdges(gids_to_remove);
+    mem_storage->indices_.vector_edge_index_.RemoveEdges(std::vector<Edge *>{edge.edge_.ptr});
```
Comment (Ignition) [inline tests/unit/vector_edge_index.cpp]: std::array

**Review by Ignition — APPROVED** [review]

File: src/storage/v2/storage.cpp (hunk 39 above)
Comment (andrejtonev) [reply src/storage/v2/storage.cpp:476]: left a TODO
