### PR TITLE
[master < T523-FL] Adding qid in bolt

### LINKED ISSUE #718: [BUG] `qid` is missing in the `Success` response for the `RUN` request
**Memgraph version**
2.5.0

**Environment**
OS: MacOS Ventura 13.1
Docker command: `docker run -it  -p 7687:7687 -p 3000:3000 memgraph/memgraph-platform:2.6.1-memgraph2.5.0-lab2.4.0`

**Describe the bug**

I'm working on a driver for the Bolt protocol. It follows the official specification and supports 3-4.4 protocols. 
The driver works fine with the corresponding Neo4j servers, for example, 3.6.2, and 4.4.3. 

The driver uses the `4.3` protocol to communicate with Memgraph and Neo4j. 

For some reason, when I execute a query within the **explicit transaction** Memgraph does not return `qid` in the `Success` message metadata. Therefore, I cannot use correlated pulls. 

The flow:
1) Send handshake packet
2) Send BEGIN packet
3) Send RUN packet. The query is `CREATE (n:Person {name: $p1, age: $p2}) RETURN n`

**Packets (hexdumps)**

<details>
  <summary><b>Memgraph 2.5.0 packets</b></summary>
  
#### 1) Handshake

Request:
```
00000000  00 37 b1 01 a2 8a 75 73  65 72 5f 61 67 65 6e 74  │.7�.��user_agent│
00000010  d0 1b 42 6f 6c 74 34 73  2f 30 2e 30 2e 38 20 28  │�.Bolt4s/0.0.8 (│
00000020  50 72 6f 74 6f 63 6f 6c  20 34 2e 33 29 86 73 63  │Protocol 4.3)�sc│
00000030  68 65 6d 65 84 6e 6f 6e  65 00 00                 │heme�none..│
00000000  b1 70 a1 8d 63 6f 6e 6e  65 63 74 69 6f 6e 5f 69  │�p��connection_i│
00000010  64 86 62 6f 6c 74 2d 31                           │d�bolt-1│
```

Response:
```
00000000  00 00 03 04                                       │....│
```

#### 2) Begin an explicit transaction

Request:
```
00000000  00 3b b1 11 a6 89 62 6f  6f 6b 6d 61 72 6b 73 90  │.;�.��bookmarks�│
00000010  8a 74 78 5f 74 69 6d 65  6f 75 74 c0 8b 74 78 5f  │�tx_timeout��tx_│
00000020  6d 65 74 61 64 61 74 61  a0 84 6d 6f 64 65 c0 82  │metadata��mode��│
00000030  64 62 c0 88 69 6d 70 5f  75 73 65 72 c0 00 00     │db��imp_user�..│
```

Response:
```
00000000  b1 70 a0                                          │�p�│
```

#### 3) Run a query

Request:
```
00000000  00 7a b3 10 d0 30 43 52  45 41 54 45 20 28 6e 3a  │.z�.�0CREATE (n:│
00000010  50 65 72 73 6f 6e 20 7b  6e 61 6d 65 3a 20 24 70  │Person {name: $p│
00000020  31 2c 20 61 67 65 3a 20  24 70 32 7d 29 20 52 45  │1, age: $p2}) RE│
00000030  54 55 52 4e 20 6e a2 82  70 31 84 41 6e 64 79 82  │TURN n��p1�Andy�│
00000040  70 32 15 a6 89 62 6f 6f  6b 6d 61 72 6b 73 90 8a  │p2.��bookmarks��│
00000050  74 78 5f 74 69 6d 65 6f  75 74 c0 8b 74 78 5f 6d  │tx_timeout��tx_m│
00000060  65 74 61 64 61 74 61 a0  84 6d 6f 64 65 c0 82 64  │etadata��mode��d│
00000070  62 c0 88 69 6d 70 5f 75  73 65 72 c0 00 00        │b��imp_user�..│
```

Response:
```
00000000  b1 70 a1 86 66 69 65 6c  64 73 91 81 6e           │�p��fields��n│
```

</details> 

<details>
  <summary><b>Neo4j 4.4.3 packets</b></summary>
  
#### 1) Handshake

Request:
```
00000000  00 37 b1 01 a2 8a 75 73  65 72 5f 61 67 65 6e 74  │.7�.��user_agent│
00000010  d0 1b 42 6f 6c 74 34 73  2f 30 2e 30 2e 38 20 28  │�.Bolt4s/0.0.8 (│
00000020  50 72 6f 74 6f 63 6f 6c  20 34 2e 33 29 86 73 63  │Protocol 4.3)�sc│
00000030  68 65 6d 65 84 6e 6f 6e  65 00 00                 │heme�none..│
00000000  b1 70 a3 86 73 65 72 76  65 72 8b 4e 65 6f 34 6a  │�p��server�Neo4j│
00000010  2f 34 2e 34 2e 33 8d 63  6f 6e 6e 65 63 74 69 6f  │/4.4.3�connectio│
00000020  6e 5f 69 64 87 62 6f 6c  74 2d 37 32 85 68 69 6e  │n_id�bolt-72�hin│
00000030  74 73 a0                                          │ts�│
```

Response:
```
00000000  00 00 03 04                                       │....│
```

#### 2) Begin an explicit transaction

Request:
```
00000000  00 3b b1 11 a6 89 62 6f  6f 6b 6d 61 72 6b 73 90  │.;�.��bookmarks�│
00000010  8a 74 78 5f 74 69 6d 65  6f 75 74 c0 8b 74 78 5f  │�tx_timeout��tx_│
00000020  6d 65 74 61 64 61 74 61  a0 84 6d 6f 64 65 c0 82  │metadata��mode��│
00000030  64 62 c0 88 69 6d 70 5f  75 73 65 72 c0 00 00     │db��imp_user�..│
```

Response:
```
00000000  b1 70 a0                                          │�p�│
```

#### 3) Run a query

Request:
```
00000000  00 7a b3 10 d0 30 43 52  45 41 54 45 20 28 6e 3a  │.z�.�0CREATE (n:│
00000010  50 65 72 73 6f 6e 20 7b  6e 61 6d 65 3a 20 24 70  │Person {name: $p│
00000020  31 2c 20 61 67 65 3a 20  24 70 32 7d 29 20 52 45  │1, age: $p2}) RE│
00000030  54 55 52 4e 20 6e a2 82  70 31 84 41 6e 64 79 82  │TURN n��p1�Andy�│
00000040  70 32 15 a6 89 62 6f 6f  6b 6d 61 72 6b 73 90 8a  │p2.��bookmarks��│
00000050  74 78 5f 74 69 6d 65 6f  75 74 c0 8b 74 78 5f 6d  │tx_timeout��tx_m│
00000060  65 74 61 64 61 74 61 a0  84 6d 6f 64 65 c0 82 64  │etadata��mode��d│
00000070  62 c0 88 69 6d 70 5f 75  73 65 72 c0 00 00        │b��imp_user�..│
```

Response:
```
00000000  b1 70 a3 87 74 5f 66 69  72 73 74 01 86 66 69 65  │�p��t_first.�fie│
00000010  6c 64 73 91 81 6e 83 71  69 64 00                 │lds��n�qid.│
```
  
</details>

Responses are pretty much identical, except the last `Success` one. Neo4j sends `t_first = 1, fields = [n], qid = 0` in the metadata, while Memgraph sends only `fields = [n]`.

**To Reproduce**
Unfortunately, the driver is proprietary, and I cannot share sources. I hope hexdumps should be enough.

**Expected behavior**
The server should assign `qid` to a query within an explicit transaction and return it in the metadata of the `Success` packet.

**Logs**
Nothing suspicious in the logs: 
```
[2022-12-15 14:55:03.946] [memgraph_log] [info] Accepted a connection from Bolt: 172.17.0.1:63316
[2022-12-15 14:55:04.006] [memgraph_log] [info] Using version 4.3 of protocol
[2022-12-15 14:55:04.144] [memgraph_log] [info] Client connected 'Bolt4s/0.0.8 (Protocol 4.3)'
[2022-12-15 14:55:04.295] [memgraph_log] [debug] [Run] 'CREATE (n:Person {name: $p1, age: $p2}) RETURN n'
```

**Additional context**
Not related to the issue, but thank you for your work! In some of my commons scenarios, Memgraph outperforms Neo4j by 20%.

### PR DESCRIPTION
**Pull request by niko4299**
[master < Task] PR
- [ ] Check, and update documentation if necessary <- @antoniofilipovic  todo
- [ ] Update [changelog](https://docs.memgraph.com/memgraph/changelog)  <- @antoniofilipovic  todo
- [x] Provide the full content or a guide for the final git message: Add qid in bolt

Closes #718

### CODE REVIEW

File: src/communication/bolt/client.hpp [hunk 1]
```diff
@@ -78,6 +78,7 @@ struct QueryData {
   std::vector<std::string> fields;
   std::vector<std::vector<Value>> records;
   std::map<std::string, Value> metadata;
+  std::int64_t qid;
```
Comment (jbajic) [inline src/communication/bolt/client.hpp:81]: This is the wrong `qid` should be a part of metadata, not a standalone value

File: src/communication/bolt/client.cpp [hunk 2]
```diff
@@ -164,6 +164,10 @@ QueryData Client::Execute(const std::string &query, const std::map<std::string,
     ret.fields.emplace_back(std::move(field_item.ValueString()));
   }
 
+  if (header.find("qid") != header.end()) {
```
Comment (jbajic) [inline src/communication/bolt/client.cpp:167]: Use contains

**Review by jbajic — CHANGES_REQUESTED** [review]

File: src/communication/bolt/client.cpp (hunk 2 above)
Comment (antaljanosbenjamin) [reply src/communication/bolt/client.cpp:167]: Of maybe
```
  if (const auto qid_it = header.find("qid"); qid_it != header.end()) {
    ret.qid = qid_it->ValueInt();
  }
```

**Review by antaljanosbenjamin — CHANGES_REQUESTED** [review]

File: src/communication/bolt/v1/states/handlers.hpp [hunk 3]
```diff
@@ -96,6 +96,10 @@ State HandleRun(TSession &session, const State state, const Value &query, const
     vec.reserve(header.size());
     for (auto &i : header) vec.emplace_back(std::move(i));
     data.emplace("fields", std::move(vec));
+    if (qid.has_value()) {
+      data.emplace("qid", Value{*qid});
+    }
+
```
[the remark this answers is not in the document]
Comment (antaljanosbenjamin) [reply src/communication/bolt/v1/states/handlers.hpp:102]: In `src/communication/bolt/v1/states/executing.hpp` you can find `StateExecutingRun` which basically the root of Bolt-related logic. It calls two functions (both of them are in the same file):
1. `RunHandlerV1` to handle Bolt version 1.
2. `RunHandlerV4` to handle Bolt version 4.0, 4.1, 4.3.
The former one calls `HandleRunV1`, the latter one calls `HandleRunV4`. Both of these functions call `details::HandleRun`, the function you just modified. I think `details::HandleRun` can have an additional template parameter (check `HandlePullDiscard` and its `is_pull` parameter, maybe we can have something similar like `bool send_qid`) and depending on that we can decide whether to fill the `qid` or not. Of course, from `HandleRunV1` we would call that with `false`, from `HandleRunV4` we can call it with `true`.

File: src/communication/bolt/v1/states/handlers.hpp [hunk 4]
```diff
@@ -96,6 +96,10 @@ State HandleRun(TSession &session, const State state, const Value &query, const
     vec.reserve(header.size());
     for (auto &i : header) vec.emplace_back(std::move(i));
     data.emplace("fields", std::move(vec));
+    if (return_qid && qid.has_value()) {
+      data.emplace("qid", Value{*qid});
+    }
+
```
Comment (jbajic) [inline src/communication/bolt/v1/states/handlers.hpp:102]: Until now this implementation of run handlers was the same but now that the `qid` was introduced I would rather separate implementations, and remove this general one (even though they will mostly be the same, this is a specific case where it makes sense to have different methods which are very similar but should be multiple of them since they are implemented for different Bolt versions)

**Comment by antoniofilipovic** [comment]
I updated this branch as I talked with @jbajic and checked whether it creates a fix with `mgclient` and it does.

File: src/communication/bolt/v1/states/handlers.hpp [hunk 5]
```diff
@@ -73,39 +73,44 @@ inline std::pair<std::string, std::string> ExceptionToErrorMessage(const std::ex
...
+//     // Send the header.
+//     if (!session.encoder_.MessageSuccess(data)) {
+//       spdlog::trace("Couldn't send query header!");
+//       return State::Close;
+//     }
+//     return State::Result;
+//   } catch (const std::exception &e) {
+//     return HandleFailure(session, e);
+//   }
+// }
```
Comment (jbajic) [inline src/communication/bolt/v1/states/handlers.hpp:113]: Please remove commented out parts

**Review by jbajic — CHANGES_REQUESTED** [review]

File: src/communication/bolt/v1/states/handlers.hpp (hunk 5 above)
Comment (antoniofilipovic) [reply src/communication/bolt/v1/states/handlers.hpp]: done, sorry, beginners mistake

**Review by jbajic — APPROVED** [review]

**Review by antaljanosbenjamin — APPROVED** [review]
